#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Assemble the speeeecies GitHub Pages site into _site/.

Copies site/*, schema/, behaviors/, species/ into the output directory,
writes <out>/species/index.json (a summary of every species/<slug>/species.json)
and <out>/ATTRIBUTION.md (a concatenation of every species/*/ATTRIBUTION.md,
with a header). Also copies AGENTS.md, CONTRIBUTING.md, ROADMAP.md, PLAN.md into
<out>/docs/ when present. Stdlib only.

Usage: python3 tools/build_site.py [--out _site] [--repo-root DIR]
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path


def repo_root_from(start: Path) -> Path:
    return start.resolve().parent


def copy_tree(src: Path, dst: Path) -> None:
    if not src.is_dir():
        return
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def build_species_index(species_dir: Path) -> list[dict]:
    entries = []
    if not species_dir.is_dir():
        return entries
    for child in sorted(species_dir.iterdir()):
        if not child.is_dir():
            continue
        species_json = child / "species.json"
        if not species_json.is_file():
            continue
        try:
            data = json.loads(species_json.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as err:
            print(f"warning: skipping {species_json}: {err}", file=sys.stderr)
            continue
        slug = data.get("slug", child.name)
        entries.append(
            {
                "slug": slug,
                "id": data.get("id", ""),
                "common_name_en": (data.get("common_names") or {}).get("en", ""),
                "class": ((data.get("taxonomy") or {}).get("class", "")),
                "body_plan": ((data.get("look") or {}).get("body_plan", "")),
                "path": f"species/{slug}/species.json",
            }
        )
    return entries


def build_attribution(species_dir: Path) -> str:
    header = (
        "# Attribution\n\n"
        "Combined attribution for every species contributed to speeeecies. "
        "Generated by tools/build_site.py; do not edit by hand.\n"
    )
    parts = [header]
    if species_dir.is_dir():
        for child in sorted(species_dir.iterdir()):
            attribution = child / "ATTRIBUTION.md"
            if attribution.is_file():
                parts.append(f"\n---\n\n## {child.name}\n\n")
                parts.append(attribution.read_text(encoding="utf-8"))
    return "".join(parts)


def build_site(repo_root: Path, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    site_src = repo_root / "site"
    if not site_src.is_dir():
        raise SystemExit(f"error: {site_src} does not exist")
    for item in site_src.iterdir():
        dst = out_dir / item.name
        if item.is_dir():
            copy_tree(item, dst)
        else:
            shutil.copy2(item, dst)

    copy_tree(repo_root / "schema", out_dir / "schema")
    copy_tree(repo_root / "behaviors", out_dir / "behaviors")
    copy_tree(repo_root / "species", out_dir / "species")

    species_dir = out_dir / "species"
    species_dir.mkdir(parents=True, exist_ok=True)
    index = build_species_index(repo_root / "species")
    (species_dir / "index.json").write_text(
        json.dumps(index, indent=2) + "\n", encoding="utf-8"
    )

    attribution = build_attribution(repo_root / "species")
    (out_dir / "ATTRIBUTION.md").write_text(attribution, encoding="utf-8")

    docs_dir = out_dir / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    for name in ("AGENTS.md", "CONTRIBUTING.md", "ROADMAP.md", "PLAN.md"):
        src = repo_root / name
        if src.is_file():
            shutil.copy2(src, docs_dir / name)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="_site", help="output directory (default: _site)")
    parser.add_argument(
        "--repo-root",
        default=None,
        help="repository root (default: parent of this script's directory)",
    )
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve() if args.repo_root else repo_root_from(Path(__file__).parent)
    out_dir = Path(args.out)
    if not out_dir.is_absolute():
        out_dir = repo_root / out_dir

    build_site(repo_root, out_dir)
    print(f"built site into {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
